In [3]:
import pandas as pd
import numpy as np

In [4]:
data = pd.read_csv("global_power_plant_database.csv")

In [5]:
data.head()

,country,country_long,name,gppd_idnr,capacity_mw,latitude,longitude,primary_fuel,other_fuel1,other_fuel2,...,url,geolocation_source,wepp_id,year_of_capacity_data,generation_gwh_2013,generation_gwh_2014,generation_gwh_2015,generation_gwh_2016,generation_gwh_2017,estimated_generation_gwh
0,AFG,Afghanistan,Kajaki Hydroelectric Power Plant Afghanistan,GEODB0040538,33.00,32.3220,65.1190,Hydro,NaN,NaN,...,http://globalenergyobservatory.org,GEODB,1009793,2017.0,NaN,NaN,NaN,NaN,NaN,NaN
1,AFG,Afghanistan,Mahipar Hydroelectric Power Plant Afghanistan,GEODB0040541,66.00,34.5560,69.4787,Hydro,NaN,NaN,...,http://globalenergyobservatory.org,GEODB,1009795,2017.0,NaN,NaN,NaN,NaN,NaN,NaN
2,AFG,Afghanistan,Naghlu Dam Hydroelectric Power Plant Afghanistan,GEODB0040534,100.00,34.6410,69.7170,Hydro,NaN,NaN,...,http://globalenergyobservatory.org,GEODB,1009797,2017.0,NaN,NaN,NaN,NaN,NaN,NaN
3,AFG,Afghanistan,Nangarhar (Darunta) Hydroelectric Power Plant ...,GEODB0040536,11.55,34.4847,70.3633,Hydro,NaN,NaN,...,http://globalenergyobservatory.org,GEODB,1009787,2017.0,NaN,NaN,NaN,NaN,NaN,NaN
4,AFG,Afghanistan,Northwest Kabul Power Plant Afghanistan,GEODB0040540,42.00,34.5638,69.1134,Gas,NaN,NaN,...,http://globalenergyobservatory.org,GEODB,NaN,2017.0,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
type(data)

pandas.core.frame.DataFrame

In [7]:
data.drop(columns = ["other_fuel1", "other_fuel2", "url", "wepp_id", "year_of_capacity_data","other_fuel3", "commissioning_year", "owner","source", "geolocation_source"], inplace = True)

In [8]:
data

,country,country_long,name,gppd_idnr,capacity_mw,latitude,longitude,primary_fuel,generation_gwh_2013,generation_gwh_2014,generation_gwh_2015,generation_gwh_2016,generation_gwh_2017,estimated_generation_gwh
0,AFG,Afghanistan,Kajaki Hydroelectric Power Plant Afghanistan,GEODB0040538,33.00,32.3220,65.1190,Hydro,NaN,NaN,NaN,NaN,NaN,NaN
1,AFG,Afghanistan,Mahipar Hydroelectric Power Plant Afghanistan,GEODB0040541,66.00,34.5560,69.4787,Hydro,NaN,NaN,NaN,NaN,NaN,NaN
2,AFG,Afghanistan,Naghlu Dam Hydroelectric Power Plant Afghanistan,GEODB0040534,100.00,34.6410,69.7170,Hydro,NaN,NaN,NaN,NaN,NaN,NaN
3,AFG,Afghanistan,Nangarhar (Darunta) Hydroelectric Power Plant ...,GEODB0040536,11.55,34.4847,70.3633,Hydro,NaN,NaN,NaN,NaN,NaN,NaN
4,AFG,Afghanistan,Northwest Kabul Power Plant Afghanistan,GEODB0040540,42.00,34.5638,69.1134,Gas,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29905,ZMB,Zambia,Ndola,WRI1022386,50.00,-12.9667,28.6333,Oil,NaN,NaN,NaN,NaN,NaN,120.872642
29906,ZMB,Zambia,Nkana,WRI1022384,20.00,-12.8167,28.2000,Oil,NaN,NaN,NaN,NaN,NaN,48.349057
29907,ZMB,Zambia,Victoria Falls,WRI1022380,108.00,-17.9167,25.8500,Hydro,NaN,NaN,NaN,NaN,NaN,702.100000
29908,ZWE,Zimbabwe,Hwange Coal Power Plant Zimbabwe,GEODB0040404,920.00,-18.3835,26.4700,Coal,NaN,NaN,NaN,NaN,NaN,4397.000000
29909,ZWE,Zimbabwe,Kariba Dam South Hydroelectric Power Station Z...,GEODB0003803,750.00,-16.5222,28.7619,Hydro,NaN,NaN,NaN,NaN,NaN,5431.000000

In [9]:
cleaned_data = data[(~pd.isna(data["estimated_generation_gwh"])) | (~pd.isna(data["generation_gwh_2013"]) | ~pd.isna(data["generation_gwh_2014"]) | ~pd.isna(data["generation_gwh_2015"]) | ~pd.isna(data["generation_gwh_2016"]) | ~pd.isna(data["generation_gwh_2017"]))]

In [10]:
cleaned_data

,country,country_long,name,gppd_idnr,capacity_mw,latitude,longitude,primary_fuel,generation_gwh_2013,generation_gwh_2014,generation_gwh_2015,generation_gwh_2016,generation_gwh_2017,estimated_generation_gwh
7,ALB,Albania,Bistrica 1,WRI1002169,27.0,39.9116,20.1047,Hydro,NaN,NaN,NaN,NaN,NaN,89.132075
8,ALB,Albania,Fierza,WRI1002170,500.0,42.2514,20.0431,Hydro,NaN,NaN,NaN,NaN,NaN,1650.593990
9,ALB,Albania,Koman,WRI1002171,600.0,42.1033,19.8224,Hydro,NaN,NaN,NaN,NaN,NaN,1980.712788
10,ALB,Albania,Lanabregas,WRI1002172,5.0,41.3428,19.8964,Hydro,NaN,NaN,NaN,NaN,NaN,16.505940
11,ALB,Albania,Shkopet,WRI1002173,24.0,41.6796,19.8305,Hydro,NaN,NaN,NaN,NaN,NaN,79.228512
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29905,ZMB,Zambia,Ndola,WRI1022386,50.0,-12.9667,28.6333,Oil,NaN,NaN,NaN,NaN,NaN,120.872642
29906,ZMB,Zambia,Nkana,WRI1022384,20.0,-12.8167,28.2000,Oil,NaN,NaN,NaN,NaN,NaN,48.349057
29907,ZMB,Zambia,Victoria Falls,WRI1022380,108.0,-17.9167,25.8500,Hydro,NaN,NaN,NaN,NaN,NaN,702.100000
29908,ZWE,Zimbabwe,Hwange Coal Power Plant Zimbabwe,GEODB0040404,920.0,-18.3835,26.4700,Coal,NaN,NaN,NaN,NaN,NaN,4397.000000
29909,ZWE,Zimbabwe,Kariba Dam South Hydroelectric Power Station Z...,GEODB0003803,750.0,-16.5222,28.7619,Hydro,NaN,NaN,NaN,NaN,NaN,5431.000000

In [11]:
cleaned_data.loc[50:100, :]

,country,country_long,name,gppd_idnr,capacity_mw,latitude,longitude,primary_fuel,generation_gwh_2013,generation_gwh_2014,generation_gwh_2015,generation_gwh_2016,generation_gwh_2017,estimated_generation_gwh
50,AGO,Angola,Capanda,WRI1023004,520.000,-9.7955,15.4672,Hydro,NaN,NaN,NaN,NaN,NaN,3401.661043
51,AGO,Angola,Cazenga,WRI1023005,132.000,-8.8383,13.2344,Gas,NaN,NaN,NaN,NaN,NaN,0.000000
52,AGO,Angola,Huambo,WRI1023006,16.260,-12.7600,15.7500,Oil,NaN,NaN,NaN,NaN,NaN,527.232579
53,AGO,Angola,Lobito,WRI1023007,20.000,-12.3700,13.5700,Gas,NaN,NaN,NaN,NaN,NaN,0.000000
54,AGO,Angola,Luanda Diesel,WRI1023008,58.000,-8.8383,13.2344,Oil,NaN,NaN,NaN,NaN,NaN,1880.657414
55,AGO,Angola,Luanda Refinery,WRI1023009,18.500,-8.8383,13.2344,Oil,NaN,NaN,NaN,NaN,NaN,599.864865
56,AGO,Angola,Malongo,WRI1023010,10.000,-5.5500,12.2000,Oil,NaN,NaN,NaN,NaN,NaN,324.251278
57,AGO,Angola,Matala,WRI1023011,40.000,-14.7333,15.0333,Hydro,NaN,NaN,NaN,NaN,NaN,261.666234
58,AGO,Angola,Namibe,WRI1023012,11.680,-15.1961,12.1522,Gas,NaN,NaN,NaN,NaN,NaN,0.000000
59,AGO,Angola,Rio Luachimo,WRI1023013,16.000,-7.3000,20.8500,Hydro,NaN,NaN,NaN,NaN,NaN,104.666494
60,AGO,Angola,Xitoto,WRI1023014,11.340,-15.3333,15.0000,Oil,NaN,NaN,NaN,NaN,NaN,367.700950
63,ARG,Argentina,AGUA DEL CAJON (AUTOGENERADOR DEL MEM),ARG0000231,479.200,-38.9368,-68.3556,Other,NaN,NaN,NaN,NaN,NaN,0.000000
64,ARG,Argentina,AGUA DEL CAJON (GENERADOR DEL MEM),ARG0000232,192.000,-38.9368,-68.3556,Gas,NaN,NaN,NaN,NaN,NaN,991.928746
65,ARG,Argentina,AGUA DEL TORO,ARG0000210,130.000,-34.5792,-68.9892,Hydro,NaN,NaN,NaN,NaN,NaN,537.539589
66,ARG,Argentina,ALICURA,ARG0000230,1050.000,-40.5800,-70.7489,Hydro,NaN,NaN,NaN,NaN,NaN,4341.665908
67,ARG,Argentina,ALMIRANTE BROWN,ARG0000156,25.000,-34.8386,-58.4033,Oil,NaN,NaN,NaN,NaN,NaN,407.324673
68,ARG,Argentina,ALTO VALLE,ARG0000235,97.500,-38.9524,-68.0218,Gas,NaN,NaN,NaN,NaN,NaN,503.713816
69,ARG,Argentina,ALUMINE,ARG0000242,1.904,-39.2145,-70.9157,Oil,NaN,NaN,NaN,NaN,NaN,31.021847
70,ARG,Argentina,ALVAREZ CONDARCO,ARG0000194,50.700,-33.0452,-69.0516,Hydro,NaN,NaN,NaN,NaN,NaN,209.640440
71,ARG,Argentina,ARROYITO,ARG0000254,128.000,-39.1009,-68.5982,Hydro,NaN,NaN,NaN,NaN,NaN,529.269749
72,ARG,Argentina,ATUCHA I,ARG0000029,370.000,-33.9670,-59.2059,Nuclear,NaN,NaN,NaN,NaN,NaN,1208.009075
73,ARG,Argentina,ATUCHA II,ARG0000030,745.000,-33.9674,-59.2045,Nuclear,NaN,NaN,NaN,NaN,NaN,2432.342598
74,ARG,Argentina,BANDERA,ARG0000328,31.000,-23.8219,-64.7847,Oil,NaN,NaN,NaN,NaN,NaN,505.082595
75,ARG,Argentina,BARILOCHE (PUERTO MORENO),ARG0000266,5.736,-41.1167,-71.4167,Oil,NaN,NaN,NaN,NaN,NaN,93.456573
76,ARG,Argentina,BENJAMIN REOLIN,ARG0000085,38.400,-32.1883,-64.3233,Hydro,NaN,NaN,NaN,NaN,NaN,158.780925
77,ARG,Argentina,BERNARDO DE IRIGOYEN,ARG0000220,2.096,-26.2545,-53.6469,Oil,NaN,NaN,NaN,NaN,NaN,34.150101
78,ARG,Argentina,C.T. RUFINO,ARG0000310,31.900,-34.2605,-62.7107,Oil,NaN,NaN,NaN,NaN,NaN,519.746283
79,ARG,Argentina,C.T. SAN VICENTE,ARG0000159,27.600,-35.0241,-58.4237,Oil,NaN,NaN,NaN,NaN,NaN,449.686439
80,ARG,Argentina,CAA CATI,ARG0000116,1.415,-27.7534,-57.6205,Oil,NaN,NaN,NaN,NaN,NaN,23.054577
81,ARG,Argentina,CABRA CORRAL,ARG0000275,102.000,-25.2712,-65.3298,Hydro,NaN,NaN,NaN,NaN,NaN,421.761831
82,ARG,Argentina,CACHEUTA (NUEVA),ARG0000195,120.000,-33.0291,-69.1109,Hydro,NaN,NaN,NaN,NaN,NaN,496.190390
83,ARG,Argentina,CACHI,ARG0000277,1.070,-25.1089,-66.2106,Oil,NaN,NaN,NaN,NaN,NaN,17.433496
84,ARG,Argentina,CAFAYATE,ARG0000278,4.182,-26.0715,-65.9876,Oil,NaN,NaN,NaN,NaN,NaN,68.137271
85,ARG,Argentina,CAPITAL CATAMARCA - PREDIO CHOYA,ARG0000048,5.728,-28.4537,-65.7841,Oil,NaN,NaN,NaN,NaN,NaN,93.326229
86,ARG,Argentina,CAPITAL CATAMARCA - PREDIO EX CARCEL,ARG0000049,7.075,-28.4773,-65.7872,Oil,NaN,NaN,NaN,NaN,NaN,115.272883
87,ARG,Argentina,CAPITAL CATAMARCA - PREDIO RIPIERA,ARG0000050,4.675,-28.4684,-65.7797,Oil,NaN,NaN,NaN,NaN,NaN,76.169714
88,ARG,Argentina,CASA DE PIEDRA,ARG0000183,60.000,-38.2143,-67.1908,Hydro,NaN,NaN,NaN,NaN,NaN,248.095195
89,ARG,Argentina,CASSAFFOUSTH,ARG0000086,17.280,-31.3992,-64.2006,Hydro,NaN,NaN,NaN,NaN,NaN,71.451416
90,ARG,Argentina,CENTRAL BAHIA BLANCA (PIEDRA BUENA) SA,ARG0000031,620.000,-38.7872,-62.2536,Coal,NaN,NaN,NaN,NaN,NaN,515.411537
91,ARG,Argentina,CENTRAL LOMA DE LA LATA SA,ARG0000259,540.000,-38.5127,-68.6048,Gas,NaN,NaN,NaN,NaN,NaN,2789.799599
92,ARG,Argentina,CENTRAL PARQUE INDUSTRIAL LA BANDA,ARG0000319,11.228,-38.0620,-67.9463,Oil,NaN,NaN,NaN,NaN,NaN,182.937657
93,ARG,Argentina,CENTRAL T.GENELBA,ARG0000165,673.600,-34.9027,-58.7334,Gas,NaN,NaN,NaN,NaN,NaN,3480.016685
94,ARG,Argentina,CENTRAL T.GENELBA PLUS,ARG0000166,164.550,-34.9027,-58.7334,Gas,NaN,NaN,NaN,NaN,NaN,850.113933
95,ARG,Argentina,CENTRAL TERMICA BRIGADIER LOPEZ (ENARSA),ARG0000311,280.000,-31.7112,-60.7811,Gas,NaN,NaN,NaN,NaN,NaN,1446.562755
96,ARG,Argentina,CENTRAL TERMICA DE CICLO COMBINADO SALTA,ARG0000274,643.000,-24.7456,-65.0513,Gas,NaN,NaN,NaN,NaN,NaN,3321.928041
97,ARG,Argentina,CENTRAL TERMICA GÃœEMES SA,ARG0000287,361.000,-24.6894,-65.0425,Coal,NaN,NaN,NaN,NaN,NaN,300.102524
98,ARG,Argentina,CENTRAL TERMICA LA BANDA,ARG0000330,32.000,-27.7528,-64.2655,Gas,NaN,NaN,NaN,NaN,NaN,165.321458
99,ARG,Argentina,CENTRAL TERMICA PIQUIRENDA SA,ARG0000284,30.440,-22.3497,-63.7664,Oil,NaN,NaN,NaN,NaN,NaN,495.958522
100,ARG,Argentina,CENTRAL TERMICA REMEDIOS DE ESCALADA,ARG0000155,25.000,-34.7208,-58.3881,Oil,NaN,NaN,NaN,NaN,NaN,407.324673

In [12]:
cleaned_data[~pd.isna(cleaned_data["generation_gwh_2017"])]

,country,country_long,name,gppd_idnr,capacity_mw,latitude,longitude,primary_fuel,generation_gwh_2013,generation_gwh_2014,generation_gwh_2015,generation_gwh_2016,generation_gwh_2017,estimated_generation_gwh
303,AUS,Australia,Albany Wind Farm,AUS0000065,21.6,-35.0641,117.7977,Wind,89.595278,102.642778,96.555556,95.872778,85.900278,NaN
305,AUS,Australia,Angaston,AUS0000232,50.0,-34.5034,139.0246,Oil,NaN,NaN,1.653056,5.300833,7.649722,526.45279
307,AUS,Australia,Appin (Mine),AUS0000264,55.6,-34.2082,150.7722,Gas,204.804444,238.294444,163.583611,158.933056,64.534722,NaN
309,AUS,Australia,Awaba,AUS0000049,1.1,-33.0250,151.5497,Waste,7.655278,8.338611,9.172500,8.830000,8.085556,NaN
310,AUS,Australia,Bairnsdale,AUS0000081,94.0,-37.8429,147.5639,Gas,132.456667,154.885556,149.821111,197.540556,168.524444,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29530,USA,United States of America,Zion Energy Center,USA0055392,596.7,42.4776,-87.8950,Gas,0.000000,63.656000,132.434005,435.493999,462.063000,NaN
29531,USA,United States of America,Zion Landfill Gas to Energy Facility,USA0056871,7.0,42.4803,-87.8861,Waste,43.592000,49.134000,46.699000,42.480000,38.669000,NaN
29532,USA,United States of America,Zorn,USA0001368,18.0,38.2803,-85.7023,Gas,0.203000,0.078000,1.058000,0.062000,0.015000,NaN
29533,USA,United States of America,Zotos International WPGF,USA0057648,3.4,42.8869,-76.9683,Wind,3.671000,2.460150,2.489000,1.670000,1.233490,NaN
29534,USA,United States of America,eBay - South Jordan,USA0059281,9.8,40.5606,-112.0478,Gas,12.968000,51.276000,71.505000,76.392000,76.631000,NaN

In [13]:
def consolidation(generation_gwh_2013, generation_gwh_2014, generation_gwh_2015, generation_gwh_2016, generation_gwh_2017, estimated_generation_gwh):
    array = np.array([generation_gwh_2013, generation_gwh_2014, generation_gwh_2015, generation_gwh_2016, generation_gwh_2017])
    array = array[~np.isnan(array)]
    if len(array) == 0:
        return estimated_generation_gwh
    else:
        
        return array.mean()

cleaned_data.loc[:, "cleaned_estimated_generation_gwh"]  = cleaned_data.apply(lambda x: 
                    consolidation(x["generation_gwh_2013"], x["generation_gwh_2014"], 
                                  x["generation_gwh_2015"], x["generation_gwh_2016"],
                                  x["generation_gwh_2017"], x["estimated_generation_gwh"]), axis=1)

C:\Users\yiyan\AppData\Local\Temp\ipykernel_27624\3785511315.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cleaned_data.loc[:, "cleaned_estimated_generation_gwh"]  = cleaned_data.apply(lambda x:

In [14]:
cleaned_data

,country,country_long,name,gppd_idnr,capacity_mw,latitude,longitude,primary_fuel,generation_gwh_2013,generation_gwh_2014,generation_gwh_2015,generation_gwh_2016,generation_gwh_2017,estimated_generation_gwh,cleaned_estimated_generation_gwh
7,ALB,Albania,Bistrica 1,WRI1002169,27.0,39.9116,20.1047,Hydro,NaN,NaN,NaN,NaN,NaN,89.132075,89.132075
8,ALB,Albania,Fierza,WRI1002170,500.0,42.2514,20.0431,Hydro,NaN,NaN,NaN,NaN,NaN,1650.593990,1650.593990
9,ALB,Albania,Koman,WRI1002171,600.0,42.1033,19.8224,Hydro,NaN,NaN,NaN,NaN,NaN,1980.712788,1980.712788
10,ALB,Albania,Lanabregas,WRI1002172,5.0,41.3428,19.8964,Hydro,NaN,NaN,NaN,NaN,NaN,16.505940,16.505940
11,ALB,Albania,Shkopet,WRI1002173,24.0,41.6796,19.8305,Hydro,NaN,NaN,NaN,NaN,NaN,79.228512,79.228512
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29905,ZMB,Zambia,Ndola,WRI1022386,50.0,-12.9667,28.6333,Oil,NaN,NaN,NaN,NaN,NaN,120.872642,120.872642
29906,ZMB,Zambia,Nkana,WRI1022384,20.0,-12.8167,28.2000,Oil,NaN,NaN,NaN,NaN,NaN,48.349057,48.349057
29907,ZMB,Zambia,Victoria Falls,WRI1022380,108.0,-17.9167,25.8500,Hydro,NaN,NaN,NaN,NaN,NaN,702.100000,702.100000
29908,ZWE,Zimbabwe,Hwange Coal Power Plant Zimbabwe,GEODB0040404,920.0,-18.3835,26.4700,Coal,NaN,NaN,NaN,NaN,NaN,4397.000000,4397.000000
29909,ZWE,Zimbabwe,Kariba Dam South Hydroelectric Power Station Z...,GEODB0003803,750.0,-16.5222,28.7619,Hydro,NaN,NaN,NaN,NaN,NaN,5431.000000,5431.000000

In [15]:
cleaned_data.drop(columns = ["generation_gwh_2013", "generation_gwh_2014", "generation_gwh_2015",
                             "generation_gwh_2016","generation_gwh_2017","estimated_generation_gwh"], inplace=True)

C:\Users\yiyan\AppData\Local\Temp\ipykernel_27624\3012203163.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cleaned_data.drop(columns = ["generation_gwh_2013", "generation_gwh_2014", "generation_gwh_2015",

In [16]:
cleaned_data

,country,country_long,name,gppd_idnr,capacity_mw,latitude,longitude,primary_fuel,cleaned_estimated_generation_gwh
7,ALB,Albania,Bistrica 1,WRI1002169,27.0,39.9116,20.1047,Hydro,89.132075
8,ALB,Albania,Fierza,WRI1002170,500.0,42.2514,20.0431,Hydro,1650.593990
9,ALB,Albania,Koman,WRI1002171,600.0,42.1033,19.8224,Hydro,1980.712788
10,ALB,Albania,Lanabregas,WRI1002172,5.0,41.3428,19.8964,Hydro,16.505940
11,ALB,Albania,Shkopet,WRI1002173,24.0,41.6796,19.8305,Hydro,79.228512
...,...,...,...,...,...,...,...,...,...
29905,ZMB,Zambia,Ndola,WRI1022386,50.0,-12.9667,28.6333,Oil,120.872642
29906,ZMB,Zambia,Nkana,WRI1022384,20.0,-12.8167,28.2000,Oil,48.349057
29907,ZMB,Zambia,Victoria Falls,WRI1022380,108.0,-17.9167,25.8500,Hydro,702.100000
29908,ZWE,Zimbabwe,Hwange Coal Power Plant Zimbabwe,GEODB0040404,920.0,-18.3835,26.4700,Coal,4397.000000
29909,ZWE,Zimbabwe,Kariba Dam South Hydroelectric Power Station Z...,GEODB0003803,750.0,-16.5222,28.7619,Hydro,5431.000000

In [17]:
cleaned_data.to_csv("cleaned_global_power_plant_database.csv", index = True)